addons:
  apt:
    packages:
    - lib32stdc++6
    - lib32z1-dev
    - gcc-multilib
    - g++-multilib
language: cpp
sudo: false
compiler:
  - clang
before_script:
  - CHECKOUT_DIR=$PWD && cd .. 
  - chmod a+x $CHECKOUT_DIR/support/checkout-deps.sh 
  - $CHECKOUT_DIR/support/checkout-deps.sh && cd $CHECKOUT_DIR
script:
  - mkdir build && cd build
  - PATH="~/.local/bin:$PATH"
  - python ../support/configure.py --enable-optimize
  - ambuild
