
version: 1.0.{build}

clone_folder: c:\projects\amxmodx

branches:
  only:
    - master
    
skip_tags: true

install:
- git submodule update --init --recursive
- 'c:'
- chdir c:\projects
- git clone https://github.com/alliedmodders/ambuild
- git clone https://github.com/alliedmodders/metamod-hl1 metamod-am
- git clone https://github.com/alliedmodders/hlsdk
- cd ambuild
- c:\python27\python setup.py install
- cd ..\amxmodx

build_script:
- '"%VS140COMNTOOLS%\vsvars32.bat"' 
- mkdir build
- cd build
- c:\python27\python ../support/configure.py --enable-optimize --disable-auto-versioning
- c:\python27\scripts\ambuild

cache:
  - ambuild
  - metamod-am
  - hlsdk
